@FnacDartyLibrary_HostAddress = http://localhost:5160

### Get All Books
GET {{FnacDartyLibrary_HostAddress}}/api/library/getAllBooks

### Add Book
POST {{FnacDartyLibrary_HostAddress}}/api/library/addBook
Content-Type: application/x-www-form-urlencoded

Title=The Lord of the Rings&Author=J.R.R. Tolkien

### Add Book - Guerre et paix
POST {{FnacDartyLibrary_HostAddress}}/api/library/addBook
Content-Type: application/json

{
  "title": "Guerre et paix",
  "author": "Leon Tolstoï"
}

