@FnacDartyLibrary_HostAddress = http://localhost:5160

### Get All Books
GET {{FnacDartyLibrary_HostAddress}}/api/library/getAllBooks

### Add Book - Guerre et paix
POST {{FnacDartyLibrary_HostAddress}}/api/library/addBook
Content-Type: application/json

{
  "title": "Guerre et paix",
  "author": "Leon Tolstoï"
}

